### ISSUE TITLE
No Issue - just one simple question

### ISSUE THREAD

**Issue by DonIvanCorleone** [TruDan/dbdiagram-oss#1]
Hi there,

thanks for your work. Looks pretty much exactly what I was looking for :)

Currently it package a small alpine docker image with your app, but realized while testing that neither Export/Save/Import are functional. Are there any plans to make at least one option for Export/Import available e.g. JSON?
Same holds true to Fit/AutoFit functionality which currently is not working. Are there plans to make this working again?

Unfortunately I am a full noob with regard to Vue.js etc. hence cannot support or provide a PR :( Sorry.

Cheers

**Comment by TruDan** [comment]
Save is functional but it saves to the browser storage. A bit misleading perhaps.

I'll look into implementing the export and import functions today, they should be quite easy :)

**Comment by DonIvanCorleone** [comment]
Woohoo!! This is awesome!! Many many thanks.

Is it equally simple to enable autofit using one of the existing jointjs
functions or is this out of scope?

Successful Sunday.

Cheers



Am 14. August 2022 10:31:31 schrieb Dan Spiteri ***@***.***>:

**Comment by DonIvanCorleone** [comment]
Hi @TruDan,

did you manage to achieve some progress?

**Comment by DonIvanCorleone** [comment]
I guess I close that ticket :)

**Comment by kashwathkumar** [comment]
Hi @TruDan - any update on the import/export? 
If you are busy - please point us to the code, we can create a PR & fix it.
